<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\AddBmpRequest\MonitoringPolicy</code>
 */
class AddBmpRequest_MonitoringPolicy
{
	/**
	 * Generated from protobuf enum <code>PRE = 0;</code>
	 */
	const PRE = 0;
	/**
	 * Generated from protobuf enum <code>POST = 1;</code>
	 */
	const POST = 1;
	/**
	 * Generated from protobuf enum <code>BOTH = 2;</code>
	 */
	const BOTH = 2;
	/**
	 * Generated from protobuf enum <code>LOCAL = 3;</code>
	 */
	const LOCAL = 3;
	/**
	 * Generated from protobuf enum <code>ALL = 4;</code>
	 */
	const ALL = 4;
}

