<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.AddPathsConfig</code>
 */
class AddPathsConfig extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>bool receive = 1;</code>
	 */
	private $receive = false;
	/**
	 * Generated from protobuf field <code>uint32 send_max = 2;</code>
	 */
	private $send_max = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>bool receive = 1;</code>
	 * @return bool
	 */
	public function getReceive()
	{
		return $this->receive;
	}

	/**
	 * Generated from protobuf field <code>bool receive = 1;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setReceive($var)
	{
		GPBUtil::checkBool($var);
		$this->receive = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 send_max = 2;</code>
	 * @return int
	 */
	public function getSendMax()
	{
		return $this->send_max;
	}

	/**
	 * Generated from protobuf field <code>uint32 send_max = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setSendMax($var)
	{
		GPBUtil::checkUint32($var);
		$this->send_max = $var;

		return $this;
	}

}

