<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.AddPathResponse</code>
 */
class AddPathResponse extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>bytes uuid = 1;</code>
	 */
	private $uuid = '';

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>bytes uuid = 1;</code>
	 * @return string
	 */
	public function getUuid()
	{
		return $this->uuid;
	}

	/**
	 * Generated from protobuf field <code>bytes uuid = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setUuid($var)
	{
		GPBUtil::checkString($var, False);
		$this->uuid = $var;

		return $this;
	}

}

