<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.AddStatementRequest</code>
 */
class AddStatementRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Statement statement = 1;</code>
	 */
	private $statement = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Statement statement = 1;</code>
	 * @return \Gobgpapi\Statement
	 */
	public function getStatement()
	{
		return $this->statement;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Statement statement = 1;</code>
	 * @param \Gobgpapi\Statement $var
	 * @return $this
	 */
	public function setStatement($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\Statement::class);
		$this->statement = $var;

		return $this;
	}

}

