<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.AddVrfRequest</code>
 */
class AddVrfRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Vrf vrf = 1;</code>
	 */
	private $vrf = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Vrf vrf = 1;</code>
	 * @return \Gobgpapi\Vrf
	 */
	public function getVrf()
	{
		return $this->vrf;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Vrf vrf = 1;</code>
	 * @param \Gobgpapi\Vrf $var
	 * @return $this
	 */
	public function setVrf($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\Vrf::class);
		$this->vrf = $var;

		return $this;
	}

}

