<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.ApplyPolicy</code>
 */
class ApplyPolicy extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyAssignment in_policy = 1;</code>
	 */
	private $in_policy = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyAssignment export_policy = 2;</code>
	 */
	private $export_policy = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyAssignment import_policy = 3;</code>
	 */
	private $import_policy = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyAssignment in_policy = 1;</code>
	 * @return \Gobgpapi\PolicyAssignment
	 */
	public function getInPolicy()
	{
		return $this->in_policy;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyAssignment in_policy = 1;</code>
	 * @param \Gobgpapi\PolicyAssignment $var
	 * @return $this
	 */
	public function setInPolicy($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\PolicyAssignment::class);
		$this->in_policy = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyAssignment export_policy = 2;</code>
	 * @return \Gobgpapi\PolicyAssignment
	 */
	public function getExportPolicy()
	{
		return $this->export_policy;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyAssignment export_policy = 2;</code>
	 * @param \Gobgpapi\PolicyAssignment $var
	 * @return $this
	 */
	public function setExportPolicy($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\PolicyAssignment::class);
		$this->export_policy = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyAssignment import_policy = 3;</code>
	 * @return \Gobgpapi\PolicyAssignment
	 */
	public function getImportPolicy()
	{
		return $this->import_policy;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyAssignment import_policy = 3;</code>
	 * @param \Gobgpapi\PolicyAssignment $var
	 * @return $this
	 */
	public function setImportPolicy($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\PolicyAssignment::class);
		$this->import_policy = $var;

		return $this;
	}

}

