<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Arguments</code>
 */
class Arguments extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource resource = 1;</code>
	 */
	private $resource = 0;
	/**
	 * Generated from protobuf field <code>uint32 family = 2;</code>
	 */
	private $family = 0;
	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 */
	private $name = '';

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource resource = 1;</code>
	 * @return int
	 */
	public function getResource()
	{
		return $this->resource;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource resource = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setResource($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\Resource::class);
		$this->resource = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 2;</code>
	 * @return int
	 */
	public function getFamily()
	{
		return $this->family;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setFamily($var)
	{
		GPBUtil::checkUint32($var);
		$this->family = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var)
	{
		GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}

}

