<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.AsPathLength</code>
 */
class AsPathLength extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.AsPathLengthType type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>uint32 length = 2;</code>
	 */
	private $length = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.AsPathLengthType type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.AsPathLengthType type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\AsPathLengthType::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 length = 2;</code>
	 * @return int
	 */
	public function getLength()
	{
		return $this->length;
	}

	/**
	 * Generated from protobuf field <code>uint32 length = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setLength($var)
	{
		GPBUtil::checkUint32($var);
		$this->length = $var;

		return $this;
	}

}

