<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\AsPathLengthType</code>
 */
class AsPathLengthType
{
	/**
	 * Generated from protobuf enum <code>EQ = 0;</code>
	 */
	const EQ = 0;
	/**
	 * Generated from protobuf enum <code>GE = 1;</code>
	 */
	const GE = 1;
	/**
	 * Generated from protobuf enum <code>LE = 2;</code>
	 */
	const LE = 2;
}

