<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\CommunityActionType</code>
 */
class CommunityActionType
{
	/**
	 * Generated from protobuf enum <code>COMMUNITY_ADD = 0;</code>
	 */
	const COMMUNITY_ADD = 0;
	/**
	 * Generated from protobuf enum <code>COMMUNITY_REMOVE = 1;</code>
	 */
	const COMMUNITY_REMOVE = 1;
	/**
	 * Generated from protobuf enum <code>COMMUNITY_REPLACE = 2;</code>
	 */
	const COMMUNITY_REPLACE = 2;
}

