<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.CommunityAction</code>
 */
class CommunityAction extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.CommunityActionType type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>repeated string communities = 2;</code>
	 */
	private $communities;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.CommunityActionType type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.CommunityActionType type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\CommunityActionType::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated string communities = 2;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getCommunities()
	{
		return $this->communities;
	}

	/**
	 * Generated from protobuf field <code>repeated string communities = 2;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setCommunities($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
		$this->communities = $arr;

		return $this;
	}

}

