<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Conditions</code>
 */
class Conditions extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet prefix_set = 1;</code>
	 */
	private $prefix_set = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet neighbor_set = 2;</code>
	 */
	private $neighbor_set = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.AsPathLength as_path_length = 3;</code>
	 */
	private $as_path_length = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet as_path_set = 4;</code>
	 */
	private $as_path_set = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet community_set = 5;</code>
	 */
	private $community_set = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet ext_community_set = 6;</code>
	 */
	private $ext_community_set = null;
	/**
	 * Generated from protobuf field <code>int32 rpki_result = 7;</code>
	 */
	private $rpki_result = 0;
	/**
	 * Generated from protobuf field <code>.gobgpapi.Conditions.RouteType route_type = 8;</code>
	 */
	private $route_type = 0;
	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet large_community_set = 9;</code>
	 */
	private $large_community_set = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet prefix_set = 1;</code>
	 * @return \Gobgpapi\MatchSet
	 */
	public function getPrefixSet()
	{
		return $this->prefix_set;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet prefix_set = 1;</code>
	 * @param \Gobgpapi\MatchSet $var
	 * @return $this
	 */
	public function setPrefixSet($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\MatchSet::class);
		$this->prefix_set = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet neighbor_set = 2;</code>
	 * @return \Gobgpapi\MatchSet
	 */
	public function getNeighborSet()
	{
		return $this->neighbor_set;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet neighbor_set = 2;</code>
	 * @param \Gobgpapi\MatchSet $var
	 * @return $this
	 */
	public function setNeighborSet($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\MatchSet::class);
		$this->neighbor_set = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.AsPathLength as_path_length = 3;</code>
	 * @return \Gobgpapi\AsPathLength
	 */
	public function getAsPathLength()
	{
		return $this->as_path_length;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.AsPathLength as_path_length = 3;</code>
	 * @param \Gobgpapi\AsPathLength $var
	 * @return $this
	 */
	public function setAsPathLength($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\AsPathLength::class);
		$this->as_path_length = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet as_path_set = 4;</code>
	 * @return \Gobgpapi\MatchSet
	 */
	public function getAsPathSet()
	{
		return $this->as_path_set;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet as_path_set = 4;</code>
	 * @param \Gobgpapi\MatchSet $var
	 * @return $this
	 */
	public function setAsPathSet($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\MatchSet::class);
		$this->as_path_set = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet community_set = 5;</code>
	 * @return \Gobgpapi\MatchSet
	 */
	public function getCommunitySet()
	{
		return $this->community_set;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet community_set = 5;</code>
	 * @param \Gobgpapi\MatchSet $var
	 * @return $this
	 */
	public function setCommunitySet($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\MatchSet::class);
		$this->community_set = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet ext_community_set = 6;</code>
	 * @return \Gobgpapi\MatchSet
	 */
	public function getExtCommunitySet()
	{
		return $this->ext_community_set;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet ext_community_set = 6;</code>
	 * @param \Gobgpapi\MatchSet $var
	 * @return $this
	 */
	public function setExtCommunitySet($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\MatchSet::class);
		$this->ext_community_set = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int32 rpki_result = 7;</code>
	 * @return int
	 */
	public function getRpkiResult()
	{
		return $this->rpki_result;
	}

	/**
	 * Generated from protobuf field <code>int32 rpki_result = 7;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setRpkiResult($var)
	{
		GPBUtil::checkInt32($var);
		$this->rpki_result = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Conditions.RouteType route_type = 8;</code>
	 * @return int
	 */
	public function getRouteType()
	{
		return $this->route_type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Conditions.RouteType route_type = 8;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setRouteType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\Conditions_RouteType::class);
		$this->route_type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet large_community_set = 9;</code>
	 * @return \Gobgpapi\MatchSet
	 */
	public function getLargeCommunitySet()
	{
		return $this->large_community_set;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MatchSet large_community_set = 9;</code>
	 * @param \Gobgpapi\MatchSet $var
	 * @return $this
	 */
	public function setLargeCommunitySet($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\MatchSet::class);
		$this->large_community_set = $var;

		return $this;
	}

}

