<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\Conditions\RouteType</code>
 */
class Conditions_RouteType
{
	/**
	 * Generated from protobuf enum <code>ROUTE_TYPE_NONE = 0;</code>
	 */
	const ROUTE_TYPE_NONE = 0;
	/**
	 * Generated from protobuf enum <code>ROUTE_TYPE_INTERNAL = 1;</code>
	 */
	const ROUTE_TYPE_INTERNAL = 1;
	/**
	 * Generated from protobuf enum <code>ROUTE_TYPE_EXTERNAL = 2;</code>
	 */
	const ROUTE_TYPE_EXTERNAL = 2;
	/**
	 * Generated from protobuf enum <code>ROUTE_TYPE_LOCAL = 3;</code>
	 */
	const ROUTE_TYPE_LOCAL = 3;
}

