<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\DefinedType</code>
 */
class DefinedType
{
	/**
	 * Generated from protobuf enum <code>PREFIX = 0;</code>
	 */
	const PREFIX = 0;
	/**
	 * Generated from protobuf enum <code>NEIGHBOR = 1;</code>
	 */
	const NEIGHBOR = 1;
	/**
	 * Generated from protobuf enum <code>TAG = 2;</code>
	 */
	const TAG = 2;
	/**
	 * Generated from protobuf enum <code>AS_PATH = 3;</code>
	 */
	const AS_PATH = 3;
	/**
	 * Generated from protobuf enum <code>COMMUNITY = 4;</code>
	 */
	const COMMUNITY = 4;
	/**
	 * Generated from protobuf enum <code>EXT_COMMUNITY = 5;</code>
	 */
	const EXT_COMMUNITY = 5;
	/**
	 * Generated from protobuf enum <code>LARGE_COMMUNITY = 6;</code>
	 */
	const LARGE_COMMUNITY = 6;
}

