<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.DefinedSet</code>
 */
class DefinedSet extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.DefinedType type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 */
	private $name = '';
	/**
	 * Generated from protobuf field <code>repeated string list = 3;</code>
	 */
	private $list;
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Prefix prefixes = 4;</code>
	 */
	private $prefixes;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.DefinedType type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.DefinedType type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\DefinedType::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var)
	{
		GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated string list = 3;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getList()
	{
		return $this->list;
	}

	/**
	 * Generated from protobuf field <code>repeated string list = 3;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setList($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
		$this->list = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Prefix prefixes = 4;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getPrefixes()
	{
		return $this->prefixes;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Prefix prefixes = 4;</code>
	 * @param \Gobgpapi\Prefix[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setPrefixes($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\Prefix::class);
		$this->prefixes = $arr;

		return $this;
	}

}

