<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.DeleteNeighborRequest</code>
 */
class DeleteNeighborRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Peer peer = 1;</code>
	 */
	private $peer = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Peer peer = 1;</code>
	 * @return \Gobgpapi\Peer
	 */
	public function getPeer()
	{
		return $this->peer;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Peer peer = 1;</code>
	 * @param \Gobgpapi\Peer $var
	 * @return $this
	 */
	public function setPeer($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\Peer::class);
		$this->peer = $var;

		return $this;
	}

}

