<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.EnableZebraRequest</code>
 */
class EnableZebraRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>string url = 1;</code>
	 */
	private $url = '';
	/**
	 * Generated from protobuf field <code>repeated string route_types = 2;</code>
	 */
	private $route_types;
	/**
	 * Generated from protobuf field <code>uint32 version = 3;</code>
	 */
	private $version = 0;
	/**
	 * Generated from protobuf field <code>bool nexthop_trigger_enable = 4;</code>
	 */
	private $nexthop_trigger_enable = false;
	/**
	 * Generated from protobuf field <code>uint32 nexthop_trigger_delay = 5;</code>
	 */
	private $nexthop_trigger_delay = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>string url = 1;</code>
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Generated from protobuf field <code>string url = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setUrl($var)
	{
		GPBUtil::checkString($var, True);
		$this->url = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated string route_types = 2;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getRouteTypes()
	{
		return $this->route_types;
	}

	/**
	 * Generated from protobuf field <code>repeated string route_types = 2;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setRouteTypes($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
		$this->route_types = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 version = 3;</code>
	 * @return int
	 */
	public function getVersion()
	{
		return $this->version;
	}

	/**
	 * Generated from protobuf field <code>uint32 version = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setVersion($var)
	{
		GPBUtil::checkUint32($var);
		$this->version = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool nexthop_trigger_enable = 4;</code>
	 * @return bool
	 */
	public function getNexthopTriggerEnable()
	{
		return $this->nexthop_trigger_enable;
	}

	/**
	 * Generated from protobuf field <code>bool nexthop_trigger_enable = 4;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setNexthopTriggerEnable($var)
	{
		GPBUtil::checkBool($var);
		$this->nexthop_trigger_enable = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 nexthop_trigger_delay = 5;</code>
	 * @return int
	 */
	public function getNexthopTriggerDelay()
	{
		return $this->nexthop_trigger_delay;
	}

	/**
	 * Generated from protobuf field <code>uint32 nexthop_trigger_delay = 5;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setNexthopTriggerDelay($var)
	{
		GPBUtil::checkUint32($var);
		$this->nexthop_trigger_delay = $var;

		return $this;
	}

}

