<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.GetDefinedSetResponse</code>
 */
class GetDefinedSetResponse extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.DefinedSet sets = 1;</code>
	 */
	private $sets;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.DefinedSet sets = 1;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getSets()
	{
		return $this->sets;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.DefinedSet sets = 1;</code>
	 * @param \Gobgpapi\DefinedSet[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setSets($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\DefinedSet::class);
		$this->sets = $arr;

		return $this;
	}

}

