<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.GetDefinedSetRequest</code>
 */
class GetDefinedSetRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.DefinedType type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 */
	private $name = '';

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.DefinedType type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.DefinedType type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\DefinedType::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var)
	{
		GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}

}

