<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.GetNeighborResponse</code>
 */
class GetNeighborResponse extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Peer peers = 1;</code>
	 */
	private $peers;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Peer peers = 1;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getPeers()
	{
		return $this->peers;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Peer peers = 1;</code>
	 * @param \Gobgpapi\Peer[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setPeers($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\Peer::class);
		$this->peers = $arr;

		return $this;
	}

}

