<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.GetPathRequest</code>
 */
class GetPathRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 */
	private $name = '';
	/**
	 * Generated from protobuf field <code>uint32 family = 3;</code>
	 */
	private $family = 0;
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.TableLookupPrefix prefixes = 4;</code>
	 */
	private $prefixes;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\Resource::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var)
	{
		GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 3;</code>
	 * @return int
	 */
	public function getFamily()
	{
		return $this->family;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setFamily($var)
	{
		GPBUtil::checkUint32($var);
		$this->family = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.TableLookupPrefix prefixes = 4;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getPrefixes()
	{
		return $this->prefixes;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.TableLookupPrefix prefixes = 4;</code>
	 * @param \Gobgpapi\TableLookupPrefix[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setPrefixes($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\TableLookupPrefix::class);
		$this->prefixes = $arr;

		return $this;
	}

}

