<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.GetPolicyResponse</code>
 */
class GetPolicyResponse extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Policy policies = 1;</code>
	 */
	private $policies;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Policy policies = 1;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getPolicies()
	{
		return $this->policies;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Policy policies = 1;</code>
	 * @param \Gobgpapi\Policy[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setPolicies($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\Policy::class);
		$this->policies = $arr;

		return $this;
	}

}

