<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.GetRibInfoRequest</code>
 */
class GetRibInfoRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.TableInfo info = 1;</code>
	 */
	private $info = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.TableInfo info = 1;</code>
	 * @return \Gobgpapi\TableInfo
	 */
	public function getInfo()
	{
		return $this->info;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.TableInfo info = 1;</code>
	 * @param \Gobgpapi\TableInfo $var
	 * @return $this
	 */
	public function setInfo($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\TableInfo::class);
		$this->info = $var;

		return $this;
	}

}

