<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.GetServerResponse</code>
 */
class GetServerResponse extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Global global = 1;</code>
	 */
	private $global = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Global global = 1;</code>
	 * @return \Gobgpapi\Global
	 */
	public function getGlobal()
	{
		return $this->global;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Global global = 1;</code>
	 * @param \Gobgpapi\Global $var
	 * @return $this
	 */
	public function setGlobal($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\Global::class);
        $this->global = $var;

        return $this;
    }

}

