<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.GetVrfResponse</code>
 */
class GetVrfResponse extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Vrf vrfs = 1;</code>
	 */
	private $vrfs;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Vrf vrfs = 1;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getVrfs()
	{
		return $this->vrfs;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Vrf vrfs = 1;</code>
	 * @param \Gobgpapi\Vrf[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setVrfs($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\Vrf::class);
		$this->vrfs = $arr;

		return $this;
	}

}

