<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Global</code>
 */
class Global extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>uint32 as = 1;</code>
	 */
	private
	$as = 0;
	/**
	 * Generated from protobuf field <code>string router_id = 2;</code>
	 */
	private
	$router_id = '';
	/**
	 * Generated from protobuf field <code>int32 listen_port = 3;</code>
	 */
	private
	$listen_port = 0;
	/**
	 * Generated from protobuf field <code>repeated string listen_addresses = 4;</code>
	 */
	private
	$listen_addresses;
	/**
	 * Generated from protobuf field <code>repeated uint32 families = 5;</code>
	 */
	private
	$families;
	/**
	 * Generated from protobuf field <code>bool use_multiple_paths = 6;</code>
	 */
	private
	$use_multiple_paths = false;

	public
	function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>uint32 as = 1;</code>
	 * @return int
	 */
	public
	function getAs()
	{
		return $this->as;
	}

	/**
	 * Generated from protobuf field <code>uint32 as = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public
	function setAs($var)
	{
		GPBUtil::checkUint32($var);
		$this->as = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string router_id = 2;</code>
	 * @return string
	 */
	public
	function getRouterId()
	{
		return $this->router_id;
	}

	/**
	 * Generated from protobuf field <code>string router_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public
	function setRouterId($var)
	{
		GPBUtil::checkString($var, True);
		$this->router_id = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int32 listen_port = 3;</code>
	 * @return int
	 */
	public
	function getListenPort()
	{
		return $this->listen_port;
	}

	/**
	 * Generated from protobuf field <code>int32 listen_port = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public
	function setListenPort($var)
	{
		GPBUtil::checkInt32($var);
		$this->listen_port = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated string listen_addresses = 4;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public
	function getListenAddresses()
	{
		return $this->listen_addresses;
	}

	/**
	 * Generated from protobuf field <code>repeated string listen_addresses = 4;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public
	function setListenAddresses($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
		$this->listen_addresses = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated uint32 families = 5;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public
	function getFamilies()
	{
		return $this->families;
	}

	/**
	 * Generated from protobuf field <code>repeated uint32 families = 5;</code>
	 * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public
	function setFamilies($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
		$this->families = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool use_multiple_paths = 6;</code>
	 * @return bool
	 */
	public
	function getUseMultiplePaths()
	{
		return $this->use_multiple_paths;
	}

	/**
	 * Generated from protobuf field <code>bool use_multiple_paths = 6;</code>
	 * @param bool $var
	 * @return $this
	 */
	public
	function setUseMultiplePaths($var)
	{
		GPBUtil::checkBool($var);
		$this->use_multiple_paths = $var;

		return $this;
	}

}

