<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.GracefulRestart</code>
 */
class GracefulRestart extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>bool enabled = 1;</code>
	 */
	private $enabled = false;
	/**
	 * Generated from protobuf field <code>uint32 restart_time = 2;</code>
	 */
	private $restart_time = 0;
	/**
	 * Generated from protobuf field <code>bool helper_only = 3;</code>
	 */
	private $helper_only = false;
	/**
	 * Generated from protobuf field <code>uint32 deferral_time = 4;</code>
	 */
	private $deferral_time = 0;
	/**
	 * Generated from protobuf field <code>bool notification_enabled = 5;</code>
	 */
	private $notification_enabled = false;
	/**
	 * Generated from protobuf field <code>bool longlived_enabled = 6;</code>
	 */
	private $longlived_enabled = false;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>bool enabled = 1;</code>
	 * @return bool
	 */
	public function getEnabled()
	{
		return $this->enabled;
	}

	/**
	 * Generated from protobuf field <code>bool enabled = 1;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setEnabled($var)
	{
		GPBUtil::checkBool($var);
		$this->enabled = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 restart_time = 2;</code>
	 * @return int
	 */
	public function getRestartTime()
	{
		return $this->restart_time;
	}

	/**
	 * Generated from protobuf field <code>uint32 restart_time = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setRestartTime($var)
	{
		GPBUtil::checkUint32($var);
		$this->restart_time = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool helper_only = 3;</code>
	 * @return bool
	 */
	public function getHelperOnly()
	{
		return $this->helper_only;
	}

	/**
	 * Generated from protobuf field <code>bool helper_only = 3;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setHelperOnly($var)
	{
		GPBUtil::checkBool($var);
		$this->helper_only = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 deferral_time = 4;</code>
	 * @return int
	 */
	public function getDeferralTime()
	{
		return $this->deferral_time;
	}

	/**
	 * Generated from protobuf field <code>uint32 deferral_time = 4;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setDeferralTime($var)
	{
		GPBUtil::checkUint32($var);
		$this->deferral_time = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool notification_enabled = 5;</code>
	 * @return bool
	 */
	public function getNotificationEnabled()
	{
		return $this->notification_enabled;
	}

	/**
	 * Generated from protobuf field <code>bool notification_enabled = 5;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setNotificationEnabled($var)
	{
		GPBUtil::checkBool($var);
		$this->notification_enabled = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool longlived_enabled = 6;</code>
	 * @return bool
	 */
	public function getLonglivedEnabled()
	{
		return $this->longlived_enabled;
	}

	/**
	 * Generated from protobuf field <code>bool longlived_enabled = 6;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setLonglivedEnabled($var)
	{
		GPBUtil::checkBool($var);
		$this->longlived_enabled = $var;

		return $this;
	}

}

