<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.IbgpConfig</code>
 */
class IbgpConfig extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>uint32 maximum_paths = 1;</code>
	 */
	private $maximum_paths = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>uint32 maximum_paths = 1;</code>
	 * @return int
	 */
	public function getMaximumPaths()
	{
		return $this->maximum_paths;
	}

	/**
	 * Generated from protobuf field <code>uint32 maximum_paths = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setMaximumPaths($var)
	{
		GPBUtil::checkUint32($var);
		$this->maximum_paths = $var;

		return $this;
	}

}

