<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.InjectMrtRequest</code>
 */
class InjectMrtRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource resource = 1;</code>
	 */
	private $resource = 0;
	/**
	 * Generated from protobuf field <code>string vrf_id = 2;</code>
	 */
	private $vrf_id = '';
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Path paths = 3;</code>
	 */
	private $paths;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource resource = 1;</code>
	 * @return int
	 */
	public function getResource()
	{
		return $this->resource;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource resource = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setResource($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\Resource::class);
		$this->resource = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string vrf_id = 2;</code>
	 * @return string
	 */
	public function getVrfId()
	{
		return $this->vrf_id;
	}

	/**
	 * Generated from protobuf field <code>string vrf_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setVrfId($var)
	{
		GPBUtil::checkString($var, True);
		$this->vrf_id = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Path paths = 3;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getPaths()
	{
		return $this->paths;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Path paths = 3;</code>
	 * @param \Gobgpapi\Path[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setPaths($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\Path::class);
		$this->paths = $arr;

		return $this;
	}

}

