<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.LongLivedGracefulRestartConfig</code>
 */
class LongLivedGracefulRestartConfig extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>bool enabled = 1;</code>
	 */
	private $enabled = false;
	/**
	 * Generated from protobuf field <code>uint32 restart_time = 2;</code>
	 */
	private $restart_time = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>bool enabled = 1;</code>
	 * @return bool
	 */
	public function getEnabled()
	{
		return $this->enabled;
	}

	/**
	 * Generated from protobuf field <code>bool enabled = 1;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setEnabled($var)
	{
		GPBUtil::checkBool($var);
		$this->enabled = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 restart_time = 2;</code>
	 * @return int
	 */
	public function getRestartTime()
	{
		return $this->restart_time;
	}

	/**
	 * Generated from protobuf field <code>uint32 restart_time = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setRestartTime($var)
	{
		GPBUtil::checkUint32($var);
		$this->restart_time = $var;

		return $this;
	}

}

