<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\MatchType</code>
 */
class MatchType
{
	/**
	 * Generated from protobuf enum <code>ANY = 0;</code>
	 */
	const ANY = 0;
	/**
	 * Generated from protobuf enum <code>ALL = 1;</code>
	 */
	const ALL = 1;
	/**
	 * Generated from protobuf enum <code>INVERT = 2;</code>
	 */
	const INVERT = 2;
}

