<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\MedActionType</code>
 */
class MedActionType
{
	/**
	 * Generated from protobuf enum <code>MED_MOD = 0;</code>
	 */
	const MED_MOD = 0;
	/**
	 * Generated from protobuf enum <code>MED_REPLACE = 1;</code>
	 */
	const MED_REPLACE = 1;
}

