<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.MedAction</code>
 */
class MedAction extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.MedActionType type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>int64 value = 2;</code>
	 */
	private $value = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MedActionType type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.MedActionType type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\MedActionType::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 value = 2;</code>
	 * @return int|string
	 */
	public function getValue()
	{
		return $this->value;
	}

	/**
	 * Generated from protobuf field <code>int64 value = 2;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setValue($var)
	{
		GPBUtil::checkInt64($var);
		$this->value = $var;

		return $this;
	}

}

