<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>uint64 NOTIFICATION = 1;</code>
	 */
	private $NOTIFICATION = 0;
	/**
	 * Generated from protobuf field <code>uint64 UPDATE = 2;</code>
	 */
	private $UPDATE = 0;
	/**
	 * Generated from protobuf field <code>uint64 OPEN = 3;</code>
	 */
	private $OPEN = 0;
	/**
	 * Generated from protobuf field <code>uint64 KEEPALIVE = 4;</code>
	 */
	private $KEEPALIVE = 0;
	/**
	 * Generated from protobuf field <code>uint64 REFRESH = 5;</code>
	 */
	private $REFRESH = 0;
	/**
	 * Generated from protobuf field <code>uint64 DISCARDED = 6;</code>
	 */
	private $DISCARDED = 0;
	/**
	 * Generated from protobuf field <code>uint64 TOTAL = 7;</code>
	 */
	private $TOTAL = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>uint64 NOTIFICATION = 1;</code>
	 * @return int|string
	 */
	public function getNOTIFICATION()
	{
		return $this->NOTIFICATION;
	}

	/**
	 * Generated from protobuf field <code>uint64 NOTIFICATION = 1;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setNOTIFICATION($var)
	{
		GPBUtil::checkUint64($var);
		$this->NOTIFICATION = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 UPDATE = 2;</code>
	 * @return int|string
	 */
	public function getUPDATE()
	{
		return $this->UPDATE;
	}

	/**
	 * Generated from protobuf field <code>uint64 UPDATE = 2;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setUPDATE($var)
	{
		GPBUtil::checkUint64($var);
		$this->UPDATE = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 OPEN = 3;</code>
	 * @return int|string
	 */
	public function getOPEN()
	{
		return $this->OPEN;
	}

	/**
	 * Generated from protobuf field <code>uint64 OPEN = 3;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setOPEN($var)
	{
		GPBUtil::checkUint64($var);
		$this->OPEN = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 KEEPALIVE = 4;</code>
	 * @return int|string
	 */
	public function getKEEPALIVE()
	{
		return $this->KEEPALIVE;
	}

	/**
	 * Generated from protobuf field <code>uint64 KEEPALIVE = 4;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setKEEPALIVE($var)
	{
		GPBUtil::checkUint64($var);
		$this->KEEPALIVE = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 REFRESH = 5;</code>
	 * @return int|string
	 */
	public function getREFRESH()
	{
		return $this->REFRESH;
	}

	/**
	 * Generated from protobuf field <code>uint64 REFRESH = 5;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setREFRESH($var)
	{
		GPBUtil::checkUint64($var);
		$this->REFRESH = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 DISCARDED = 6;</code>
	 * @return int|string
	 */
	public function getDISCARDED()
	{
		return $this->DISCARDED;
	}

	/**
	 * Generated from protobuf field <code>uint64 DISCARDED = 6;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setDISCARDED($var)
	{
		GPBUtil::checkUint64($var);
		$this->DISCARDED = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 TOTAL = 7;</code>
	 * @return int|string
	 */
	public function getTOTAL()
	{
		return $this->TOTAL;
	}

	/**
	 * Generated from protobuf field <code>uint64 TOTAL = 7;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setTOTAL($var)
	{
		GPBUtil::checkUint64($var);
		$this->TOTAL = $var;

		return $this;
	}

}

