<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.MonitorRibRequest</code>
 */
class MonitorRibRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Table table = 1;</code>
	 */
	private $table = null;
	/**
	 * Generated from protobuf field <code>bool current = 2;</code>
	 */
	private $current = false;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Table table = 1;</code>
	 * @return \Gobgpapi\Table
	 */
	public function getTable()
	{
		return $this->table;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Table table = 1;</code>
	 * @param \Gobgpapi\Table $var
	 * @return $this
	 */
	public function setTable($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\Table::class);
		$this->table = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool current = 2;</code>
	 * @return bool
	 */
	public function getCurrent()
	{
		return $this->current;
	}

	/**
	 * Generated from protobuf field <code>bool current = 2;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setCurrent($var)
	{
		GPBUtil::checkBool($var);
		$this->current = $var;

		return $this;
	}

}

