<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.MpGracefulRestartState</code>
 */
class MpGracefulRestartState extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>bool enabled = 1;</code>
	 */
	private $enabled = false;
	/**
	 * Generated from protobuf field <code>bool received = 2;</code>
	 */
	private $received = false;
	/**
	 * Generated from protobuf field <code>bool advertised = 3;</code>
	 */
	private $advertised = false;
	/**
	 * Generated from protobuf field <code>bool end_of_rib_received = 4;</code>
	 */
	private $end_of_rib_received = false;
	/**
	 * Generated from protobuf field <code>bool end_of_rib_sent = 5;</code>
	 */
	private $end_of_rib_sent = false;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>bool enabled = 1;</code>
	 * @return bool
	 */
	public function getEnabled()
	{
		return $this->enabled;
	}

	/**
	 * Generated from protobuf field <code>bool enabled = 1;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setEnabled($var)
	{
		GPBUtil::checkBool($var);
		$this->enabled = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool received = 2;</code>
	 * @return bool
	 */
	public function getReceived()
	{
		return $this->received;
	}

	/**
	 * Generated from protobuf field <code>bool received = 2;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setReceived($var)
	{
		GPBUtil::checkBool($var);
		$this->received = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool advertised = 3;</code>
	 * @return bool
	 */
	public function getAdvertised()
	{
		return $this->advertised;
	}

	/**
	 * Generated from protobuf field <code>bool advertised = 3;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setAdvertised($var)
	{
		GPBUtil::checkBool($var);
		$this->advertised = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool end_of_rib_received = 4;</code>
	 * @return bool
	 */
	public function getEndOfRibReceived()
	{
		return $this->end_of_rib_received;
	}

	/**
	 * Generated from protobuf field <code>bool end_of_rib_received = 4;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setEndOfRibReceived($var)
	{
		GPBUtil::checkBool($var);
		$this->end_of_rib_received = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool end_of_rib_sent = 5;</code>
	 * @return bool
	 */
	public function getEndOfRibSent()
	{
		return $this->end_of_rib_sent;
	}

	/**
	 * Generated from protobuf field <code>bool end_of_rib_sent = 5;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setEndOfRibSent($var)
	{
		GPBUtil::checkBool($var);
		$this->end_of_rib_sent = $var;

		return $this;
	}

}

