<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Path</code>
 */
class Path extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>bytes nlri = 1;</code>
	 */
	private $nlri = '';
	/**
	 * Generated from protobuf field <code>repeated bytes pattrs = 2;</code>
	 */
	private $pattrs;
	/**
	 * Generated from protobuf field <code>int64 age = 3;</code>
	 */
	private $age = 0;
	/**
	 * Generated from protobuf field <code>bool best = 4;</code>
	 */
	private $best = false;
	/**
	 * Generated from protobuf field <code>bool is_withdraw = 5;</code>
	 */
	private $is_withdraw = false;
	/**
	 * remains for backword compatibility
	 *
	 * Generated from protobuf field <code>int32 validation = 6;</code>
	 */
	private $validation = 0;
	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIValidation validation_detail = 7;</code>
	 */
	private $validation_detail = null;
	/**
	 * Generated from protobuf field <code>bool no_implicit_withdraw = 8;</code>
	 */
	private $no_implicit_withdraw = false;
	/**
	 * Generated from protobuf field <code>uint32 family = 9;</code>
	 */
	private $family = 0;
	/**
	 * Generated from protobuf field <code>uint32 source_asn = 10;</code>
	 */
	private $source_asn = 0;
	/**
	 * Generated from protobuf field <code>string source_id = 11;</code>
	 */
	private $source_id = '';
	/**
	 * Generated from protobuf field <code>bool filtered = 12;</code>
	 */
	private $filtered = false;
	/**
	 * Generated from protobuf field <code>bool stale = 13;</code>
	 */
	private $stale = false;
	/**
	 * Generated from protobuf field <code>bool is_from_external = 14;</code>
	 */
	private $is_from_external = false;
	/**
	 * Generated from protobuf field <code>string neighbor_ip = 15;</code>
	 */
	private $neighbor_ip = '';
	/**
	 * only paths installed by AddPath API have this
	 *
	 * Generated from protobuf field <code>bytes uuid = 16;</code>
	 */
	private $uuid = '';
	/**
	 * Generated from protobuf field <code>bool is_nexthop_invalid = 17;</code>
	 */
	private $is_nexthop_invalid = false;
	/**
	 * Generated from protobuf field <code>uint32 identifier = 18;</code>
	 */
	private $identifier = 0;
	/**
	 * Generated from protobuf field <code>uint32 local_identifier = 19;</code>
	 */
	private $local_identifier = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>bytes nlri = 1;</code>
	 * @return string
	 */
	public function getNlri()
	{
		return $this->nlri;
	}

	/**
	 * Generated from protobuf field <code>bytes nlri = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setNlri($var)
	{
		GPBUtil::checkString($var, False);
		$this->nlri = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated bytes pattrs = 2;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getPattrs()
	{
		return $this->pattrs;
	}

	/**
	 * Generated from protobuf field <code>repeated bytes pattrs = 2;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setPattrs($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
		$this->pattrs = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 age = 3;</code>
	 * @return int|string
	 */
	public function getAge()
	{
		return $this->age;
	}

	/**
	 * Generated from protobuf field <code>int64 age = 3;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setAge($var)
	{
		GPBUtil::checkInt64($var);
		$this->age = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool best = 4;</code>
	 * @return bool
	 */
	public function getBest()
	{
		return $this->best;
	}

	/**
	 * Generated from protobuf field <code>bool best = 4;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setBest($var)
	{
		GPBUtil::checkBool($var);
		$this->best = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool is_withdraw = 5;</code>
	 * @return bool
	 */
	public function getIsWithdraw()
	{
		return $this->is_withdraw;
	}

	/**
	 * Generated from protobuf field <code>bool is_withdraw = 5;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setIsWithdraw($var)
	{
		GPBUtil::checkBool($var);
		$this->is_withdraw = $var;

		return $this;
	}

	/**
	 * remains for backword compatibility
	 *
	 * Generated from protobuf field <code>int32 validation = 6;</code>
	 * @return int
	 */
	public function getValidation()
	{
		return $this->validation;
	}

	/**
	 * remains for backword compatibility
	 *
	 * Generated from protobuf field <code>int32 validation = 6;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setValidation($var)
	{
		GPBUtil::checkInt32($var);
		$this->validation = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIValidation validation_detail = 7;</code>
	 * @return \Gobgpapi\RPKIValidation
	 */
	public function getValidationDetail()
	{
		return $this->validation_detail;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIValidation validation_detail = 7;</code>
	 * @param \Gobgpapi\RPKIValidation $var
	 * @return $this
	 */
	public function setValidationDetail($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\RPKIValidation::class);
		$this->validation_detail = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool no_implicit_withdraw = 8;</code>
	 * @return bool
	 */
	public function getNoImplicitWithdraw()
	{
		return $this->no_implicit_withdraw;
	}

	/**
	 * Generated from protobuf field <code>bool no_implicit_withdraw = 8;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setNoImplicitWithdraw($var)
	{
		GPBUtil::checkBool($var);
		$this->no_implicit_withdraw = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 9;</code>
	 * @return int
	 */
	public function getFamily()
	{
		return $this->family;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 9;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setFamily($var)
	{
		GPBUtil::checkUint32($var);
		$this->family = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 source_asn = 10;</code>
	 * @return int
	 */
	public function getSourceAsn()
	{
		return $this->source_asn;
	}

	/**
	 * Generated from protobuf field <code>uint32 source_asn = 10;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setSourceAsn($var)
	{
		GPBUtil::checkUint32($var);
		$this->source_asn = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string source_id = 11;</code>
	 * @return string
	 */
	public function getSourceId()
	{
		return $this->source_id;
	}

	/**
	 * Generated from protobuf field <code>string source_id = 11;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setSourceId($var)
	{
		GPBUtil::checkString($var, True);
		$this->source_id = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool filtered = 12;</code>
	 * @return bool
	 */
	public function getFiltered()
	{
		return $this->filtered;
	}

	/**
	 * Generated from protobuf field <code>bool filtered = 12;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setFiltered($var)
	{
		GPBUtil::checkBool($var);
		$this->filtered = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool stale = 13;</code>
	 * @return bool
	 */
	public function getStale()
	{
		return $this->stale;
	}

	/**
	 * Generated from protobuf field <code>bool stale = 13;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setStale($var)
	{
		GPBUtil::checkBool($var);
		$this->stale = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool is_from_external = 14;</code>
	 * @return bool
	 */
	public function getIsFromExternal()
	{
		return $this->is_from_external;
	}

	/**
	 * Generated from protobuf field <code>bool is_from_external = 14;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setIsFromExternal($var)
	{
		GPBUtil::checkBool($var);
		$this->is_from_external = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string neighbor_ip = 15;</code>
	 * @return string
	 */
	public function getNeighborIp()
	{
		return $this->neighbor_ip;
	}

	/**
	 * Generated from protobuf field <code>string neighbor_ip = 15;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setNeighborIp($var)
	{
		GPBUtil::checkString($var, True);
		$this->neighbor_ip = $var;

		return $this;
	}

	/**
	 * only paths installed by AddPath API have this
	 *
	 * Generated from protobuf field <code>bytes uuid = 16;</code>
	 * @return string
	 */
	public function getUuid()
	{
		return $this->uuid;
	}

	/**
	 * only paths installed by AddPath API have this
	 *
	 * Generated from protobuf field <code>bytes uuid = 16;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setUuid($var)
	{
		GPBUtil::checkString($var, False);
		$this->uuid = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool is_nexthop_invalid = 17;</code>
	 * @return bool
	 */
	public function getIsNexthopInvalid()
	{
		return $this->is_nexthop_invalid;
	}

	/**
	 * Generated from protobuf field <code>bool is_nexthop_invalid = 17;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setIsNexthopInvalid($var)
	{
		GPBUtil::checkBool($var);
		$this->is_nexthop_invalid = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 identifier = 18;</code>
	 * @return int
	 */
	public function getIdentifier()
	{
		return $this->identifier;
	}

	/**
	 * Generated from protobuf field <code>uint32 identifier = 18;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setIdentifier($var)
	{
		GPBUtil::checkUint32($var);
		$this->identifier = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 local_identifier = 19;</code>
	 * @return int
	 */
	public function getLocalIdentifier()
	{
		return $this->local_identifier;
	}

	/**
	 * Generated from protobuf field <code>uint32 local_identifier = 19;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setLocalIdentifier($var)
	{
		GPBUtil::checkUint32($var);
		$this->local_identifier = $var;

		return $this;
	}

}

