<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\PeerConf\RemovePrivateAs</code>
 */
class PeerConf_RemovePrivateAs
{
	/**
	 * Generated from protobuf enum <code>NONE = 0;</code>
	 */
	const NONE = 0;
	/**
	 * Generated from protobuf enum <code>ALL = 1;</code>
	 */
	const ALL = 1;
	/**
	 * Generated from protobuf enum <code>REPLACE = 2;</code>
	 */
	const REPLACE = 2;
}

