<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\PeerState\AdminState</code>
 */
class PeerState_AdminState
{
	/**
	 * Generated from protobuf enum <code>UP = 0;</code>
	 */
	const UP = 0;
	/**
	 * Generated from protobuf enum <code>DOWN = 1;</code>
	 */
	const DOWN = 1;
	/**
	 * prefix counter over limit
	 *
	 * Generated from protobuf enum <code>PFX_CT = 2;</code>
	 */
	const PFX_CT = 2;
}

