<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.PeerConf</code>
 */
class PeerConf extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>string auth_password = 1;</code>
	 */
	private $auth_password = '';
	/**
	 * Generated from protobuf field <code>string description = 2;</code>
	 */
	private $description = '';
	/**
	 * Generated from protobuf field <code>uint32 local_as = 3;</code>
	 */
	private $local_as = 0;
	/**
	 * Generated from protobuf field <code>string neighbor_address = 4;</code>
	 */
	private $neighbor_address = '';
	/**
	 * Generated from protobuf field <code>uint32 peer_as = 5;</code>
	 */
	private $peer_as = 0;
	/**
	 * Generated from protobuf field <code>string peer_group = 6;</code>
	 */
	private $peer_group = '';
	/**
	 * Generated from protobuf field <code>uint32 peer_type = 7;</code>
	 */
	private $peer_type = 0;
	/**
	 * Generated from protobuf field <code>.gobgpapi.PeerConf.RemovePrivateAs remove_private_as = 8;</code>
	 */
	private $remove_private_as = 0;
	/**
	 * Generated from protobuf field <code>bool route_flap_damping = 9;</code>
	 */
	private $route_flap_damping = false;
	/**
	 * Generated from protobuf field <code>uint32 send_community = 10;</code>
	 */
	private $send_community = 0;
	/**
	 * Generated from protobuf field <code>repeated bytes remote_cap = 11;</code>
	 */
	private $remote_cap;
	/**
	 * Generated from protobuf field <code>repeated bytes local_cap = 12;</code>
	 */
	private $local_cap;
	/**
	 * Generated from protobuf field <code>string id = 13;</code>
	 */
	private $id = '';
	/**
	 * Note: Regarding to the consistency with OpenConfig mode, list of
	 * PrefixLimit should be removed from here, and list of PrefixLimit in
	 * AfiSafi should be used instead.
	 *
	 * Generated from protobuf field <code>repeated .gobgpapi.PrefixLimit prefix_limits = 14;</code>
	 */
	private $prefix_limits;
	/**
	 * Generated from protobuf field <code>string local_address = 15;</code>
	 */
	private $local_address = '';
	/**
	 * Generated from protobuf field <code>string neighbor_interface = 16;</code>
	 */
	private $neighbor_interface = '';
	/**
	 * Generated from protobuf field <code>string vrf = 17;</code>
	 */
	private $vrf = '';
	/**
	 * Generated from protobuf field <code>uint32 allow_own_as = 18;</code>
	 */
	private $allow_own_as = 0;
	/**
	 * Generated from protobuf field <code>bool replace_peer_as = 19;</code>
	 */
	private $replace_peer_as = false;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>string auth_password = 1;</code>
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->auth_password;
	}

	/**
	 * Generated from protobuf field <code>string auth_password = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setAuthPassword($var)
	{
		GPBUtil::checkString($var, True);
		$this->auth_password = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string description = 2;</code>
	 * @return string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Generated from protobuf field <code>string description = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setDescription($var)
	{
		GPBUtil::checkString($var, True);
		$this->description = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 local_as = 3;</code>
	 * @return int
	 */
	public function getLocalAs()
	{
		return $this->local_as;
	}

	/**
	 * Generated from protobuf field <code>uint32 local_as = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setLocalAs($var)
	{
		GPBUtil::checkUint32($var);
		$this->local_as = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string neighbor_address = 4;</code>
	 * @return string
	 */
	public function getNeighborAddress()
	{
		return $this->neighbor_address;
	}

	/**
	 * Generated from protobuf field <code>string neighbor_address = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setNeighborAddress($var)
	{
		GPBUtil::checkString($var, True);
		$this->neighbor_address = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 peer_as = 5;</code>
	 * @return int
	 */
	public function getPeerAs()
	{
		return $this->peer_as;
	}

	/**
	 * Generated from protobuf field <code>uint32 peer_as = 5;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setPeerAs($var)
	{
		GPBUtil::checkUint32($var);
		$this->peer_as = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string peer_group = 6;</code>
	 * @return string
	 */
	public function getPeerGroup()
	{
		return $this->peer_group;
	}

	/**
	 * Generated from protobuf field <code>string peer_group = 6;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setPeerGroup($var)
	{
		GPBUtil::checkString($var, True);
		$this->peer_group = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 peer_type = 7;</code>
	 * @return int
	 */
	public function getPeerType()
	{
		return $this->peer_type;
	}

	/**
	 * Generated from protobuf field <code>uint32 peer_type = 7;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setPeerType($var)
	{
		GPBUtil::checkUint32($var);
		$this->peer_type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PeerConf.RemovePrivateAs remove_private_as = 8;</code>
	 * @return int
	 */
	public function getRemovePrivateAs()
	{
		return $this->remove_private_as;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PeerConf.RemovePrivateAs remove_private_as = 8;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setRemovePrivateAs($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\PeerConf_RemovePrivateAs::class);
		$this->remove_private_as = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool route_flap_damping = 9;</code>
	 * @return bool
	 */
	public function getRouteFlapDamping()
	{
		return $this->route_flap_damping;
	}

	/**
	 * Generated from protobuf field <code>bool route_flap_damping = 9;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setRouteFlapDamping($var)
	{
		GPBUtil::checkBool($var);
		$this->route_flap_damping = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 send_community = 10;</code>
	 * @return int
	 */
	public function getSendCommunity()
	{
		return $this->send_community;
	}

	/**
	 * Generated from protobuf field <code>uint32 send_community = 10;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setSendCommunity($var)
	{
		GPBUtil::checkUint32($var);
		$this->send_community = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated bytes remote_cap = 11;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getRemoteCap()
	{
		return $this->remote_cap;
	}

	/**
	 * Generated from protobuf field <code>repeated bytes remote_cap = 11;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setRemoteCap($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
		$this->remote_cap = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated bytes local_cap = 12;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getLocalCap()
	{
		return $this->local_cap;
	}

	/**
	 * Generated from protobuf field <code>repeated bytes local_cap = 12;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setLocalCap($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
		$this->local_cap = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string id = 13;</code>
	 * @return string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Generated from protobuf field <code>string id = 13;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setId($var)
	{
		GPBUtil::checkString($var, True);
		$this->id = $var;

		return $this;
	}

	/**
	 * Note: Regarding to the consistency with OpenConfig mode, list of
	 * PrefixLimit should be removed from here, and list of PrefixLimit in
	 * AfiSafi should be used instead.
	 *
	 * Generated from protobuf field <code>repeated .gobgpapi.PrefixLimit prefix_limits = 14;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getPrefixLimits()
	{
		return $this->prefix_limits;
	}

	/**
	 * Note: Regarding to the consistency with OpenConfig mode, list of
	 * PrefixLimit should be removed from here, and list of PrefixLimit in
	 * AfiSafi should be used instead.
	 *
	 * Generated from protobuf field <code>repeated .gobgpapi.PrefixLimit prefix_limits = 14;</code>
	 * @param \Gobgpapi\PrefixLimit[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setPrefixLimits($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\PrefixLimit::class);
		$this->prefix_limits = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string local_address = 15;</code>
	 * @return string
	 */
	public function getLocalAddress()
	{
		return $this->local_address;
	}

	/**
	 * Generated from protobuf field <code>string local_address = 15;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setLocalAddress($var)
	{
		GPBUtil::checkString($var, True);
		$this->local_address = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string neighbor_interface = 16;</code>
	 * @return string
	 */
	public function getNeighborInterface()
	{
		return $this->neighbor_interface;
	}

	/**
	 * Generated from protobuf field <code>string neighbor_interface = 16;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setNeighborInterface($var)
	{
		GPBUtil::checkString($var, True);
		$this->neighbor_interface = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string vrf = 17;</code>
	 * @return string
	 */
	public function getVrf()
	{
		return $this->vrf;
	}

	/**
	 * Generated from protobuf field <code>string vrf = 17;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setVrf($var)
	{
		GPBUtil::checkString($var, True);
		$this->vrf = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 allow_own_as = 18;</code>
	 * @return int
	 */
	public function getAllowOwnAs()
	{
		return $this->allow_own_as;
	}

	/**
	 * Generated from protobuf field <code>uint32 allow_own_as = 18;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setAllowOwnAs($var)
	{
		GPBUtil::checkUint32($var);
		$this->allow_own_as = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool replace_peer_as = 19;</code>
	 * @return bool
	 */
	public function getReplacePeerAs()
	{
		return $this->replace_peer_as;
	}

	/**
	 * Generated from protobuf field <code>bool replace_peer_as = 19;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setReplacePeerAs($var)
	{
		GPBUtil::checkBool($var);
		$this->replace_peer_as = $var;

		return $this;
	}

}

