<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Peer</code>
 */
class Peer extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>repeated uint32 families = 1;</code>
	 */
	private $families;
	/**
	 * Generated from protobuf field <code>.gobgpapi.ApplyPolicy apply_policy = 2;</code>
	 */
	private $apply_policy = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.PeerConf conf = 3;</code>
	 */
	private $conf = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.EbgpMultihop ebgp_multihop = 4;</code>
	 */
	private $ebgp_multihop = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.RouteReflector route_reflector = 5;</code>
	 */
	private $route_reflector = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.PeerState info = 6;</code>
	 */
	private $info = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.Timers timers = 7;</code>
	 */
	private $timers = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.Transport transport = 8;</code>
	 */
	private $transport = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.RouteServer route_server = 9;</code>
	 */
	private $route_server = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.GracefulRestart graceful_restart = 10;</code>
	 */
	private $graceful_restart = null;
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.AfiSafi afi_safis = 11;</code>
	 */
	private $afi_safis;
	/**
	 * Generated from protobuf field <code>.gobgpapi.AddPaths add_paths = 12;</code>
	 */
	private $add_paths = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>repeated uint32 families = 1;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getFamilies()
	{
		return $this->families;
	}

	/**
	 * Generated from protobuf field <code>repeated uint32 families = 1;</code>
	 * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setFamilies($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
		$this->families = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.ApplyPolicy apply_policy = 2;</code>
	 * @return \Gobgpapi\ApplyPolicy
	 */
	public function getApplyPolicy()
	{
		return $this->apply_policy;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.ApplyPolicy apply_policy = 2;</code>
	 * @param \Gobgpapi\ApplyPolicy $var
	 * @return $this
	 */
	public function setApplyPolicy($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\ApplyPolicy::class);
		$this->apply_policy = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PeerConf conf = 3;</code>
	 * @return \Gobgpapi\PeerConf
	 */
	public function getConf()
	{
		return $this->conf;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PeerConf conf = 3;</code>
	 * @param \Gobgpapi\PeerConf $var
	 * @return $this
	 */
	public function setConf($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\PeerConf::class);
		$this->conf = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.EbgpMultihop ebgp_multihop = 4;</code>
	 * @return \Gobgpapi\EbgpMultihop
	 */
	public function getEbgpMultihop()
	{
		return $this->ebgp_multihop;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.EbgpMultihop ebgp_multihop = 4;</code>
	 * @param \Gobgpapi\EbgpMultihop $var
	 * @return $this
	 */
	public function setEbgpMultihop($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\EbgpMultihop::class);
		$this->ebgp_multihop = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RouteReflector route_reflector = 5;</code>
	 * @return \Gobgpapi\RouteReflector
	 */
	public function getRouteReflector()
	{
		return $this->route_reflector;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RouteReflector route_reflector = 5;</code>
	 * @param \Gobgpapi\RouteReflector $var
	 * @return $this
	 */
	public function setRouteReflector($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\RouteReflector::class);
		$this->route_reflector = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PeerState info = 6;</code>
	 * @return \Gobgpapi\PeerState
	 */
	public function getInfo()
	{
		return $this->info;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PeerState info = 6;</code>
	 * @param \Gobgpapi\PeerState $var
	 * @return $this
	 */
	public function setInfo($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\PeerState::class);
		$this->info = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Timers timers = 7;</code>
	 * @return \Gobgpapi\Timers
	 */
	public function getTimers()
	{
		return $this->timers;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Timers timers = 7;</code>
	 * @param \Gobgpapi\Timers $var
	 * @return $this
	 */
	public function setTimers($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\Timers::class);
		$this->timers = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Transport transport = 8;</code>
	 * @return \Gobgpapi\Transport
	 */
	public function getTransport()
	{
		return $this->transport;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Transport transport = 8;</code>
	 * @param \Gobgpapi\Transport $var
	 * @return $this
	 */
	public function setTransport($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\Transport::class);
		$this->transport = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RouteServer route_server = 9;</code>
	 * @return \Gobgpapi\RouteServer
	 */
	public function getRouteServer()
	{
		return $this->route_server;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RouteServer route_server = 9;</code>
	 * @param \Gobgpapi\RouteServer $var
	 * @return $this
	 */
	public function setRouteServer($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\RouteServer::class);
		$this->route_server = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.GracefulRestart graceful_restart = 10;</code>
	 * @return \Gobgpapi\GracefulRestart
	 */
	public function getGracefulRestart()
	{
		return $this->graceful_restart;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.GracefulRestart graceful_restart = 10;</code>
	 * @param \Gobgpapi\GracefulRestart $var
	 * @return $this
	 */
	public function setGracefulRestart($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\GracefulRestart::class);
		$this->graceful_restart = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.AfiSafi afi_safis = 11;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getAfiSafis()
	{
		return $this->afi_safis;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.AfiSafi afi_safis = 11;</code>
	 * @param \Gobgpapi\AfiSafi[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setAfiSafis($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\AfiSafi::class);
		$this->afi_safis = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.AddPaths add_paths = 12;</code>
	 * @return \Gobgpapi\AddPaths
	 */
	public function getAddPaths()
	{
		return $this->add_paths;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.AddPaths add_paths = 12;</code>
	 * @param \Gobgpapi\AddPaths $var
	 * @return $this
	 */
	public function setAddPaths($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\AddPaths::class);
		$this->add_paths = $var;

		return $this;
	}

}

