<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\PolicyType</code>
 */
class PolicyType
{
	/**
	 * Generated from protobuf enum <code>IN = 0;</code>
	 */
	const IN = 0;
	/**
	 * Generated from protobuf enum <code>IMPORT = 1;</code>
	 */
	const IMPORT = 1;
	/**
	 * Generated from protobuf enum <code>EXPORT = 2;</code>
	 */
	const EXPORT = 2;
}

