<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.PolicyAssignment</code>
 */
class PolicyAssignment extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyType type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource resource = 2;</code>
	 */
	private $resource = 0;
	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 */
	private $name = '';
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Policy policies = 4;</code>
	 */
	private $policies;
	/**
	 * Generated from protobuf field <code>.gobgpapi.RouteAction default = 5;</code>
	 */
	private $default = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyType type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.PolicyType type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\PolicyType::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource resource = 2;</code>
	 * @return int
	 */
	public function getResource()
	{
		return $this->resource;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource resource = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setResource($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\Resource::class);
		$this->resource = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var)
	{
		GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Policy policies = 4;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getPolicies()
	{
		return $this->policies;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Policy policies = 4;</code>
	 * @param \Gobgpapi\Policy[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setPolicies($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\Policy::class);
		$this->policies = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RouteAction default = 5;</code>
	 * @return int
	 */
	public function getDefault()
	{
		return $this->default;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RouteAction default = 5;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setDefault($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\RouteAction::class);
		$this->default = $var;

		return $this;
	}

}

