<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Queues</code>
 */
class Queues extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>uint32 input = 1;</code>
	 */
	private $input = 0;
	/**
	 * Generated from protobuf field <code>uint32 output = 2;</code>
	 */
	private $output = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>uint32 input = 1;</code>
	 * @return int
	 */
	public function getInput()
	{
		return $this->input;
	}

	/**
	 * Generated from protobuf field <code>uint32 input = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setInput($var)
	{
		GPBUtil::checkUint32($var);
		$this->input = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 output = 2;</code>
	 * @return int
	 */
	public function getOutput()
	{
		return $this->output;
	}

	/**
	 * Generated from protobuf field <code>uint32 output = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setOutput($var)
	{
		GPBUtil::checkUint32($var);
		$this->output = $var;

		return $this;
	}

}

