<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\Resource</code>
 */
class Resource
{
	/**
	 * Generated from protobuf enum <code>GLOBAL = 0;</code>
	 */
	const GLOBAL = 0;
	/**
	 * Generated from protobuf enum <code>LOCAL = 1;</code>
	 */
	const LOCAL = 1;
	/**
	 * Generated from protobuf enum <code>ADJ_IN = 2;</code>
	 */
	const ADJ_IN = 2;
	/**
	 * Generated from protobuf enum <code>ADJ_OUT = 3;</code>
	 */
	const ADJ_OUT = 3;
	/**
	 * Generated from protobuf enum <code>VRF = 4;</code>
	 */
	const VRF = 4;
}

