<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Roa</code>
 */
class Roa extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>uint32 as = 1;</code>
	 */
	private $as = 0;
	/**
	 * Generated from protobuf field <code>uint32 prefixlen = 2;</code>
	 */
	private $prefixlen = 0;
	/**
	 * Generated from protobuf field <code>uint32 maxlen = 3;</code>
	 */
	private $maxlen = 0;
	/**
	 * Generated from protobuf field <code>string prefix = 4;</code>
	 */
	private $prefix = '';
	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIConf conf = 5;</code>
	 */
	private $conf = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>uint32 as = 1;</code>
	 * @return int
	 */
	public function getAs()
	{
		return $this->as;
	}

	/**
	 * Generated from protobuf field <code>uint32 as = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setAs($var)
	{
		GPBUtil::checkUint32($var);
		$this->as = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 prefixlen = 2;</code>
	 * @return int
	 */
	public function getPrefixlen()
	{
		return $this->prefixlen;
	}

	/**
	 * Generated from protobuf field <code>uint32 prefixlen = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setPrefixlen($var)
	{
		GPBUtil::checkUint32($var);
		$this->prefixlen = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 maxlen = 3;</code>
	 * @return int
	 */
	public function getMaxlen()
	{
		return $this->maxlen;
	}

	/**
	 * Generated from protobuf field <code>uint32 maxlen = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setMaxlen($var)
	{
		GPBUtil::checkUint32($var);
		$this->maxlen = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string prefix = 4;</code>
	 * @return string
	 */
	public function getPrefix()
	{
		return $this->prefix;
	}

	/**
	 * Generated from protobuf field <code>string prefix = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setPrefix($var)
	{
		GPBUtil::checkString($var, True);
		$this->prefix = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIConf conf = 5;</code>
	 * @return \Gobgpapi\RPKIConf
	 */
	public function getConf()
	{
		return $this->conf;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIConf conf = 5;</code>
	 * @param \Gobgpapi\RPKIConf $var
	 * @return $this
	 */
	public function setConf($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\RPKIConf::class);
		$this->conf = $var;

		return $this;
	}

}

