<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.RouteTargetMembershipConfig</code>
 */
class RouteTargetMembershipConfig extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>uint32 deferral_time = 1;</code>
	 */
	private $deferral_time = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>uint32 deferral_time = 1;</code>
	 * @return int
	 */
	public function getDeferralTime()
	{
		return $this->deferral_time;
	}

	/**
	 * Generated from protobuf field <code>uint32 deferral_time = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setDeferralTime($var)
	{
		GPBUtil::checkUint32($var);
		$this->deferral_time = $var;

		return $this;
	}

}

