<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\RouteAction</code>
 */
class RouteAction
{
	/**
	 * Generated from protobuf enum <code>NONE = 0;</code>
	 */
	const NONE = 0;
	/**
	 * Generated from protobuf enum <code>ACCEPT = 1;</code>
	 */
	const ACCEPT = 1;
	/**
	 * Generated from protobuf enum <code>REJECT = 2;</code>
	 */
	const REJECT = 2;
}

