<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.RouteServer</code>
 */
class RouteServer extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>bool route_server_client = 1;</code>
	 */
	private $route_server_client = false;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>bool route_server_client = 1;</code>
	 * @return bool
	 */
	public function getRouteServerClient()
	{
		return $this->route_server_client;
	}

	/**
	 * Generated from protobuf field <code>bool route_server_client = 1;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setRouteServerClient($var)
	{
		GPBUtil::checkBool($var);
		$this->route_server_client = $var;

		return $this;
	}

}

