<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.RouteReflector</code>
 */
class RouteReflector extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>bool route_reflector_client = 1;</code>
	 */
	private $route_reflector_client = false;
	/**
	 * Generated from protobuf field <code>string route_reflector_cluster_id = 2;</code>
	 */
	private $route_reflector_cluster_id = '';

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>bool route_reflector_client = 1;</code>
	 * @return bool
	 */
	public function getRouteReflectorClient()
	{
		return $this->route_reflector_client;
	}

	/**
	 * Generated from protobuf field <code>bool route_reflector_client = 1;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setRouteReflectorClient($var)
	{
		GPBUtil::checkBool($var);
		$this->route_reflector_client = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string route_reflector_cluster_id = 2;</code>
	 * @return string
	 */
	public function getRouteReflectorClusterId()
	{
		return $this->route_reflector_cluster_id;
	}

	/**
	 * Generated from protobuf field <code>string route_reflector_cluster_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setRouteReflectorClusterId($var)
	{
		GPBUtil::checkString($var, True);
		$this->route_reflector_cluster_id = $var;

		return $this;
	}

}

