<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Rpki</code>
 */
class Rpki extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIConf conf = 1;</code>
	 */
	private $conf = null;
	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIState state = 2;</code>
	 */
	private $state = null;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIConf conf = 1;</code>
	 * @return \Gobgpapi\RPKIConf
	 */
	public function getConf()
	{
		return $this->conf;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIConf conf = 1;</code>
	 * @param \Gobgpapi\RPKIConf $var
	 * @return $this
	 */
	public function setConf($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\RPKIConf::class);
		$this->conf = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIState state = 2;</code>
	 * @return \Gobgpapi\RPKIState
	 */
	public function getState()
	{
		return $this->state;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.RPKIState state = 2;</code>
	 * @param \Gobgpapi\RPKIState $var
	 * @return $this
	 */
	public function setState($var)
	{
		GPBUtil::checkMessage($var, \Gobgpapi\RPKIState::class);
		$this->state = $var;

		return $this;
	}

}

