<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.RPKIState</code>
 */
class RPKIState extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>int64 uptime = 1;</code>
	 */
	private $uptime = 0;
	/**
	 * Generated from protobuf field <code>int64 downtime = 2;</code>
	 */
	private $downtime = 0;
	/**
	 * Generated from protobuf field <code>bool up = 3;</code>
	 */
	private $up = false;
	/**
	 * Generated from protobuf field <code>uint32 record_ipv4 = 4;</code>
	 */
	private $record_ipv4 = 0;
	/**
	 * Generated from protobuf field <code>uint32 record_ipv6 = 5;</code>
	 */
	private $record_ipv6 = 0;
	/**
	 * Generated from protobuf field <code>uint32 prefix_ipv4 = 6;</code>
	 */
	private $prefix_ipv4 = 0;
	/**
	 * Generated from protobuf field <code>uint32 prefix_ipv6 = 7;</code>
	 */
	private $prefix_ipv6 = 0;
	/**
	 * Generated from protobuf field <code>uint32 serial = 8;</code>
	 */
	private $serial = 0;
	/**
	 * Generated from protobuf field <code>int64 received_ipv4 = 9;</code>
	 */
	private $received_ipv4 = 0;
	/**
	 * Generated from protobuf field <code>int64 received_ipv6 = 10;</code>
	 */
	private $received_ipv6 = 0;
	/**
	 * Generated from protobuf field <code>int64 serial_notify = 11;</code>
	 */
	private $serial_notify = 0;
	/**
	 * Generated from protobuf field <code>int64 cache_reset = 12;</code>
	 */
	private $cache_reset = 0;
	/**
	 * Generated from protobuf field <code>int64 cache_response = 13;</code>
	 */
	private $cache_response = 0;
	/**
	 * Generated from protobuf field <code>int64 end_of_data = 14;</code>
	 */
	private $end_of_data = 0;
	/**
	 * Generated from protobuf field <code>int64 error = 15;</code>
	 */
	private $error = 0;
	/**
	 * Generated from protobuf field <code>int64 serial_query = 16;</code>
	 */
	private $serial_query = 0;
	/**
	 * Generated from protobuf field <code>int64 reset_query = 17;</code>
	 */
	private $reset_query = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>int64 uptime = 1;</code>
	 * @return int|string
	 */
	public function getUptime()
	{
		return $this->uptime;
	}

	/**
	 * Generated from protobuf field <code>int64 uptime = 1;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setUptime($var)
	{
		GPBUtil::checkInt64($var);
		$this->uptime = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 downtime = 2;</code>
	 * @return int|string
	 */
	public function getDowntime()
	{
		return $this->downtime;
	}

	/**
	 * Generated from protobuf field <code>int64 downtime = 2;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setDowntime($var)
	{
		GPBUtil::checkInt64($var);
		$this->downtime = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool up = 3;</code>
	 * @return bool
	 */
	public function getUp()
	{
		return $this->up;
	}

	/**
	 * Generated from protobuf field <code>bool up = 3;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setUp($var)
	{
		GPBUtil::checkBool($var);
		$this->up = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 record_ipv4 = 4;</code>
	 * @return int
	 */
	public function getRecordIpv4()
	{
		return $this->record_ipv4;
	}

	/**
	 * Generated from protobuf field <code>uint32 record_ipv4 = 4;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setRecordIpv4($var)
	{
		GPBUtil::checkUint32($var);
		$this->record_ipv4 = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 record_ipv6 = 5;</code>
	 * @return int
	 */
	public function getRecordIpv6()
	{
		return $this->record_ipv6;
	}

	/**
	 * Generated from protobuf field <code>uint32 record_ipv6 = 5;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setRecordIpv6($var)
	{
		GPBUtil::checkUint32($var);
		$this->record_ipv6 = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 prefix_ipv4 = 6;</code>
	 * @return int
	 */
	public function getPrefixIpv4()
	{
		return $this->prefix_ipv4;
	}

	/**
	 * Generated from protobuf field <code>uint32 prefix_ipv4 = 6;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setPrefixIpv4($var)
	{
		GPBUtil::checkUint32($var);
		$this->prefix_ipv4 = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 prefix_ipv6 = 7;</code>
	 * @return int
	 */
	public function getPrefixIpv6()
	{
		return $this->prefix_ipv6;
	}

	/**
	 * Generated from protobuf field <code>uint32 prefix_ipv6 = 7;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setPrefixIpv6($var)
	{
		GPBUtil::checkUint32($var);
		$this->prefix_ipv6 = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 serial = 8;</code>
	 * @return int
	 */
	public function getSerial()
	{
		return $this->serial;
	}

	/**
	 * Generated from protobuf field <code>uint32 serial = 8;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setSerial($var)
	{
		GPBUtil::checkUint32($var);
		$this->serial = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 received_ipv4 = 9;</code>
	 * @return int|string
	 */
	public function getReceivedIpv4()
	{
		return $this->received_ipv4;
	}

	/**
	 * Generated from protobuf field <code>int64 received_ipv4 = 9;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setReceivedIpv4($var)
	{
		GPBUtil::checkInt64($var);
		$this->received_ipv4 = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 received_ipv6 = 10;</code>
	 * @return int|string
	 */
	public function getReceivedIpv6()
	{
		return $this->received_ipv6;
	}

	/**
	 * Generated from protobuf field <code>int64 received_ipv6 = 10;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setReceivedIpv6($var)
	{
		GPBUtil::checkInt64($var);
		$this->received_ipv6 = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 serial_notify = 11;</code>
	 * @return int|string
	 */
	public function getSerialNotify()
	{
		return $this->serial_notify;
	}

	/**
	 * Generated from protobuf field <code>int64 serial_notify = 11;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setSerialNotify($var)
	{
		GPBUtil::checkInt64($var);
		$this->serial_notify = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 cache_reset = 12;</code>
	 * @return int|string
	 */
	public function getCacheReset()
	{
		return $this->cache_reset;
	}

	/**
	 * Generated from protobuf field <code>int64 cache_reset = 12;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setCacheReset($var)
	{
		GPBUtil::checkInt64($var);
		$this->cache_reset = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 cache_response = 13;</code>
	 * @return int|string
	 */
	public function getCacheResponse()
	{
		return $this->cache_response;
	}

	/**
	 * Generated from protobuf field <code>int64 cache_response = 13;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setCacheResponse($var)
	{
		GPBUtil::checkInt64($var);
		$this->cache_response = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 end_of_data = 14;</code>
	 * @return int|string
	 */
	public function getEndOfData()
	{
		return $this->end_of_data;
	}

	/**
	 * Generated from protobuf field <code>int64 end_of_data = 14;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setEndOfData($var)
	{
		GPBUtil::checkInt64($var);
		$this->end_of_data = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 error = 15;</code>
	 * @return int|string
	 */
	public function getError()
	{
		return $this->error;
	}

	/**
	 * Generated from protobuf field <code>int64 error = 15;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setError($var)
	{
		GPBUtil::checkInt64($var);
		$this->error = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 serial_query = 16;</code>
	 * @return int|string
	 */
	public function getSerialQuery()
	{
		return $this->serial_query;
	}

	/**
	 * Generated from protobuf field <code>int64 serial_query = 16;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setSerialQuery($var)
	{
		GPBUtil::checkInt64($var);
		$this->serial_query = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>int64 reset_query = 17;</code>
	 * @return int|string
	 */
	public function getResetQuery()
	{
		return $this->reset_query;
	}

	/**
	 * Generated from protobuf field <code>int64 reset_query = 17;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setResetQuery($var)
	{
		GPBUtil::checkInt64($var);
		$this->reset_query = $var;

		return $this;
	}

}

