<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.RPKIConf</code>
 */
class RPKIConf extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>string address = 1;</code>
	 */
	private $address = '';
	/**
	 * Generated from protobuf field <code>string remote_port = 2;</code>
	 */
	private $remote_port = '';

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>string address = 1;</code>
	 * @return string
	 */
	public function getAddress()
	{
		return $this->address;
	}

	/**
	 * Generated from protobuf field <code>string address = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setAddress($var)
	{
		GPBUtil::checkString($var, True);
		$this->address = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string remote_port = 2;</code>
	 * @return string
	 */
	public function getRemotePort()
	{
		return $this->remote_port;
	}

	/**
	 * Generated from protobuf field <code>string remote_port = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setRemotePort($var)
	{
		GPBUtil::checkString($var, True);
		$this->remote_port = $var;

		return $this;
	}

}

