<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\RPKIValidation\State</code>
 */
class RPKIValidation_State
{
	/**
	 * Generated from protobuf enum <code>STATE_NONE = 0;</code>
	 */
	const STATE_NONE = 0;
	/**
	 * Generated from protobuf enum <code>STATE_NOT_FOUND = 1;</code>
	 */
	const STATE_NOT_FOUND = 1;
	/**
	 * Generated from protobuf enum <code>STATE_VALID = 2;</code>
	 */
	const STATE_VALID = 2;
	/**
	 * Generated from protobuf enum <code>STATE_INVALID = 3;</code>
	 */
	const STATE_INVALID = 3;
}

