<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\RPKIValidation\Reason</code>
 */
class RPKIValidation_Reason
{
	/**
	 * Generated from protobuf enum <code>REASOT_NONE = 0;</code>
	 */
	const REASOT_NONE = 0;
	/**
	 * Generated from protobuf enum <code>REASON_AS = 1;</code>
	 */
	const REASON_AS = 1;
	/**
	 * Generated from protobuf enum <code>REASON_LENGTH = 2;</code>
	 */
	const REASON_LENGTH = 2;
}

