<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * Protobuf enum <code>Gobgpapi\SoftResetNeighborRequest\SoftResetDirection</code>
 */
class SoftResetNeighborRequest_SoftResetDirection
{
	/**
	 * Generated from protobuf enum <code>IN = 0;</code>
	 */
	const IN = 0;
	/**
	 * Generated from protobuf enum <code>OUT = 1;</code>
	 */
	const OUT = 1;
	/**
	 * Generated from protobuf enum <code>BOTH = 2;</code>
	 */
	const BOTH = 2;
}

