<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * API representation of table.LookupPrefix
 *
 * Generated from protobuf message <code>gobgpapi.TableLookupPrefix</code>
 */
class TableLookupPrefix extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>string prefix = 1;</code>
	 */
	private $prefix = '';
	/**
	 * Generated from protobuf field <code>.gobgpapi.TableLookupOption lookup_option = 2;</code>
	 */
	private $lookup_option = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>string prefix = 1;</code>
	 * @return string
	 */
	public function getPrefix()
	{
		return $this->prefix;
	}

	/**
	 * Generated from protobuf field <code>string prefix = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setPrefix($var)
	{
		GPBUtil::checkString($var, True);
		$this->prefix = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.TableLookupOption lookup_option = 2;</code>
	 * @return int
	 */
	public function getLookupOption()
	{
		return $this->lookup_option;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.TableLookupOption lookup_option = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setLookupOption($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\TableLookupOption::class);
		$this->lookup_option = $var;

		return $this;
	}

}

