<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

/**
 * API representation of table.LookupOption
 *
 * Protobuf enum <code>Gobgpapi\TableLookupOption</code>
 */
class TableLookupOption
{
	/**
	 * Generated from protobuf enum <code>LOOKUP_EXACT = 0;</code>
	 */
	const LOOKUP_EXACT = 0;
	/**
	 * Generated from protobuf enum <code>LOOKUP_LONGER = 1;</code>
	 */
	const LOOKUP_LONGER = 1;
	/**
	 * Generated from protobuf enum <code>LOOKUP_SHORTER = 2;</code>
	 */
	const LOOKUP_SHORTER = 2;
}

