<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.Table</code>
 */
class Table extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 */
	private $name = '';
	/**
	 * Generated from protobuf field <code>uint32 family = 3;</code>
	 */
	private $family = 0;
	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Destination destinations = 4;</code>
	 */
	private $destinations;
	/**
	 * Generated from protobuf field <code>bool post_policy = 5;</code>
	 */
	private $post_policy = false;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\Resource::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var)
	{
		GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 3;</code>
	 * @return int
	 */
	public function getFamily()
	{
		return $this->family;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setFamily($var)
	{
		GPBUtil::checkUint32($var);
		$this->family = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Destination destinations = 4;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getDestinations()
	{
		return $this->destinations;
	}

	/**
	 * Generated from protobuf field <code>repeated .gobgpapi.Destination destinations = 4;</code>
	 * @param \Gobgpapi\Destination[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setDestinations($var)
	{
		$arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gobgpapi\Destination::class);
		$this->destinations = $arr;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>bool post_policy = 5;</code>
	 * @return bool
	 */
	public function getPostPolicy()
	{
		return $this->post_policy;
	}

	/**
	 * Generated from protobuf field <code>bool post_policy = 5;</code>
	 * @param bool $var
	 * @return $this
	 */
	public function setPostPolicy($var)
	{
		GPBUtil::checkBool($var);
		$this->post_policy = $var;

		return $this;
	}

}

