<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.TableInfo</code>
 */
class TableInfo extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 */
	private $name = '';
	/**
	 * Generated from protobuf field <code>uint32 family = 3;</code>
	 */
	private $family = 0;
	/**
	 * Generated from protobuf field <code>uint64 num_destination = 4;</code>
	 */
	private $num_destination = 0;
	/**
	 * Generated from protobuf field <code>uint64 num_path = 5;</code>
	 */
	private $num_path = 0;
	/**
	 * only meaningful when type == ADJ_IN
	 *
	 * Generated from protobuf field <code>uint64 num_accepted = 6;</code>
	 */
	private $num_accepted = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\Resource::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Generated from protobuf field <code>string name = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var)
	{
		GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 3;</code>
	 * @return int
	 */
	public function getFamily()
	{
		return $this->family;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setFamily($var)
	{
		GPBUtil::checkUint32($var);
		$this->family = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 num_destination = 4;</code>
	 * @return int|string
	 */
	public function getNumDestination()
	{
		return $this->num_destination;
	}

	/**
	 * Generated from protobuf field <code>uint64 num_destination = 4;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setNumDestination($var)
	{
		GPBUtil::checkUint64($var);
		$this->num_destination = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 num_path = 5;</code>
	 * @return int|string
	 */
	public function getNumPath()
	{
		return $this->num_path;
	}

	/**
	 * Generated from protobuf field <code>uint64 num_path = 5;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setNumPath($var)
	{
		GPBUtil::checkUint64($var);
		$this->num_path = $var;

		return $this;
	}

	/**
	 * only meaningful when type == ADJ_IN
	 *
	 * Generated from protobuf field <code>uint64 num_accepted = 6;</code>
	 * @return int|string
	 */
	public function getNumAccepted()
	{
		return $this->num_accepted;
	}

	/**
	 * only meaningful when type == ADJ_IN
	 *
	 * Generated from protobuf field <code>uint64 num_accepted = 6;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setNumAccepted($var)
	{
		GPBUtil::checkUint64($var);
		$this->num_accepted = $var;

		return $this;
	}

}

