<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.TimersState</code>
 */
class TimersState extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>uint64 connect_retry = 1;</code>
	 */
	private $connect_retry = 0;
	/**
	 * Generated from protobuf field <code>uint64 hold_time = 2;</code>
	 */
	private $hold_time = 0;
	/**
	 * Generated from protobuf field <code>uint64 keepalive_interval = 3;</code>
	 */
	private $keepalive_interval = 0;
	/**
	 * Generated from protobuf field <code>uint64 minimum_advertisement_interval = 4;</code>
	 */
	private $minimum_advertisement_interval = 0;
	/**
	 * Generated from protobuf field <code>uint64 negotiated_hold_time = 5;</code>
	 */
	private $negotiated_hold_time = 0;
	/**
	 * Generated from protobuf field <code>uint64 uptime = 6;</code>
	 */
	private $uptime = 0;
	/**
	 * Generated from protobuf field <code>uint64 downtime = 7;</code>
	 */
	private $downtime = 0;

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>uint64 connect_retry = 1;</code>
	 * @return int|string
	 */
	public function getConnectRetry()
	{
		return $this->connect_retry;
	}

	/**
	 * Generated from protobuf field <code>uint64 connect_retry = 1;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setConnectRetry($var)
	{
		GPBUtil::checkUint64($var);
		$this->connect_retry = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 hold_time = 2;</code>
	 * @return int|string
	 */
	public function getHoldTime()
	{
		return $this->hold_time;
	}

	/**
	 * Generated from protobuf field <code>uint64 hold_time = 2;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setHoldTime($var)
	{
		GPBUtil::checkUint64($var);
		$this->hold_time = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 keepalive_interval = 3;</code>
	 * @return int|string
	 */
	public function getKeepaliveInterval()
	{
		return $this->keepalive_interval;
	}

	/**
	 * Generated from protobuf field <code>uint64 keepalive_interval = 3;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setKeepaliveInterval($var)
	{
		GPBUtil::checkUint64($var);
		$this->keepalive_interval = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 minimum_advertisement_interval = 4;</code>
	 * @return int|string
	 */
	public function getMinimumAdvertisementInterval()
	{
		return $this->minimum_advertisement_interval;
	}

	/**
	 * Generated from protobuf field <code>uint64 minimum_advertisement_interval = 4;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setMinimumAdvertisementInterval($var)
	{
		GPBUtil::checkUint64($var);
		$this->minimum_advertisement_interval = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 negotiated_hold_time = 5;</code>
	 * @return int|string
	 */
	public function getNegotiatedHoldTime()
	{
		return $this->negotiated_hold_time;
	}

	/**
	 * Generated from protobuf field <code>uint64 negotiated_hold_time = 5;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setNegotiatedHoldTime($var)
	{
		GPBUtil::checkUint64($var);
		$this->negotiated_hold_time = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 uptime = 6;</code>
	 * @return int|string
	 */
	public function getUptime()
	{
		return $this->uptime;
	}

	/**
	 * Generated from protobuf field <code>uint64 uptime = 6;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setUptime($var)
	{
		GPBUtil::checkUint64($var);
		$this->uptime = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint64 downtime = 7;</code>
	 * @return int|string
	 */
	public function getDowntime()
	{
		return $this->downtime;
	}

	/**
	 * Generated from protobuf field <code>uint64 downtime = 7;</code>
	 * @param int|string $var
	 * @return $this
	 */
	public function setDowntime($var)
	{
		GPBUtil::checkUint64($var);
		$this->downtime = $var;

		return $this;
	}

}

