<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

namespace Gobgpapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gobgpapi.ValidateRibRequest</code>
 */
class ValidateRibRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 */
	private $type = 0;
	/**
	 * Generated from protobuf field <code>uint32 family = 2;</code>
	 */
	private $family = 0;
	/**
	 * Generated from protobuf field <code>string prefix = 3;</code>
	 */
	private $prefix = '';

	public function __construct()
	{
		\GPBMetadata\Gobgp::initOnce();
		parent::__construct();
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Generated from protobuf field <code>.gobgpapi.Resource type = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setType($var)
	{
		GPBUtil::checkEnum($var, \Gobgpapi\Resource::class);
		$this->type = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 2;</code>
	 * @return int
	 */
	public function getFamily()
	{
		return $this->family;
	}

	/**
	 * Generated from protobuf field <code>uint32 family = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setFamily($var)
	{
		GPBUtil::checkUint32($var);
		$this->family = $var;

		return $this;
	}

	/**
	 * Generated from protobuf field <code>string prefix = 3;</code>
	 * @return string
	 */
	public function getPrefix()
	{
		return $this->prefix;
	}

	/**
	 * Generated from protobuf field <code>string prefix = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setPrefix($var)
	{
		GPBUtil::checkString($var, True);
		$this->prefix = $var;

		return $this;
	}

}

